### PR TITLE
Marwan prac1

### PR DESCRIPTION
**Pull request by marwansubhi**
added some comments to be reviewed by the team

### CODE REVIEW

**Comment by marwansubhi** [comment]
hi everyone

**Comment by egemenelz** [comment]
Hello Marwan

**Comment by marwansubhi** [comment]
what do you think guys?

**Comment by marwansubhi** [comment]
can you check it again

**Comment by Bakhtiar-Semseddin** [comment]
Can you add me

**Comment by devruslan** [comment]
this is awesome

**Pull request merged**
